spring.application.name=PersonalFinanceTracker
server.port = 4567

spring.datasource.url = jdbc:mysql://localhost:3306/personalfinancetracker_db
spring.datasource.username = root
spring.datasource.password = root

spring.jpa.hibernate.ddl-auto = update

spring.jpa.show-sql = true